export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  ADMINISTRADOR = 'ROL_ADMINISTRADOR',
  VENDEDOR = 'ROL_VENDEDOR',
  PROFESOR = 'ROL_PROFESOR',
  INSTRUCTOR = 'ROL_INSTRUCTOR',
}
